@id=2
@token= {{login.response.body.token}}

####################################
# Register user
####################################
POST http://127.0.0.1:3001/api/register
Content-Type: application/json

{
	"email": "test@test.com",
	"password": "admin"
}

####################################
# Login user
####################################
# @name login
POST http://127.0.0.1:3001/api/login
Content-Type: application/json

{
	"email": "test@test.com",
	"password": "admin"
}


####################################
# Get all books
####################################
GET http://127.0.0.1:3000/api/books

####################################
# Get book with id
####################################
GET http://127.0.0.1:3000/api/books/4

####################################
# Add book
####################################
POST http://127.0.0.1:3000/api/books
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "The Hobbit 5",
  "author": "J.R.R. Tolkien",
  "publishedYear": 1938
}

####################################
# Delete book
####################################
DELETE  http://127.0.0.1:3000/api/books/11
Authorization: Bearer {{token}}


